export const BLOG = {
    POST: 'POST',
    REMOVE_POST: 'REMOVE_POST',
    EDIT_POST: 'EDIT_POST'
}

export const SERVICE_API = {
    TEST_LOADING: 'TEST/LOADING',
    TEST_SUCCESS: 'TEST/SUCCESS',
    TEST_ERROR: 'TEST/ERROR',

    GET_TODOS_LOADING: 'GET/LOADING',
    GET_TODOS_SUCCESS: 'GET/SUCCESS',
    GET_TODOS_ERROR: 'GET/ERROR',
};

